---
output:
  pdf_document: default
  html_document: default
---



```{r, lendo os dados, echo=FALSE, warning=FALSE, message=FALSE}
library(car)
library(MASS)
library(plyr)
library(gridExtra)
library(ggplot2)
library(xtable)
library(devtools)

dados <- read.table("moscas_0_1.txt", header = TRUE)
attach(dados)
especie <- dados[,1]
n <- nrow(dados)
mx <- as.matrix(dados[,2:8])
nvar <- 7
inames <- c("comprimento da asa","largura da asa","comprimento do 3 palpo","largura do 3 palpo","comprimento do 2 palpo","comprimento do 12 segmento da antena", "comprimento do 13 segmento da antena")
dadosd <- dados[,2:8]
```


```{r, análise de Componentes Principais via Matriz de Correlações, echo=FALSE}
dadosaux <- dados
p <- ncol(dadosd)
m.cor <- cor(dadosd)
aut.val <-  eigen(m.cor)$values
aut.vec <- (eigen(m.cor)$vectors)
m.aut.val <- t(matrix(((aut.val)),p,p))
result.cp.cor <- princomp(dadosd,cor=TRUE)
corr.cp.cor <- aut.vec*sqrt(m.aut.val)
# usamos só 3 componentes, que já cobre quase 77% da variância
#xtable(summary(result.cp.cor))

screeplot(result.cp.cor,type=c("lines"),main="autovalores",cex=1.2,cex.lab=1.2,cex.main=1.2)

#tabela 2.2 do trab da nat valores são; result.cp.cor$loadings , (corr.cp.cor)


cp1 <-  cbind((result.cp.cor$scores)[,1])
cp2 <-  cbind((result.cp.cor$scores)[,2])
cp3 <- cbind((result.cp.cor$scores)[,3])

cp3 <- cp3*-1


# dispersão entre as componentes
especie <- as.character(dadosaux[,1]) 
mycolors <- c("black", "black")
plot(data.frame(cp1,cp2,cp3), col=mycolors[factor(especie)], pch = c(4,16))

############# VERIFICAR BOXPLOT CP3 E HISTOGRAMAS #############

# Por grupo
par(mfrow=c(1,3))
boxplot(cp1~especie,cex=1.2,cex.lab=1.2,xlab="CP1")
boxplot(cp2~especie,cex=1.2,cex.lab=1.2,xlab="CP2")
boxplot(cp3~especie,cex=1.2,cex.lab=1.2,xlab="CP3");abline(-0.3169562,0,lty=2)

par(mfrow=c(3,2))
hist(cp1[especie=="0"], freq=TRUE, xlim=c(-6,6), ylim=c(0,20), breaks=6, main="CP1",xlab="",ylab="")
hist(cp1[especie=="1"], freq=TRUE, xlim=c(-6,6), ylim=c(0,20), breaks=8, main="CP1",xlab="",ylab="")
hist(cp2[especie=="0"], freq=TRUE, xlim=c(-6,6), ylim=c(0,20), breaks=6,main="CP2",xlab="",ylab="")
hist(cp2[especie=="1"], freq=TRUE, xlim=c(-6,6), ylim=c(0,20), breaks=6,main="CP2",xlab="",ylab="")
hist(cp3[especie=="0"], freq=TRUE, xlim=c(-6,6), ylim=c(0,20), breaks=4,main="CP3",xlab="",ylab="")
hist(cp3[especie=="1"], freq=TRUE, xlim=c(-6,6), ylim=c(0,20), breaks=4,main="CP3",xlab="",ylab="")


```
\begin{center}
  \begin{tabular}{l c c c c c c c}
     \hline
     Componente & 1 & 2 & 3 & 4 & 5 & 6 & 7 \\ \hline
     Desvio Padrão & 1,71 & 1,24 & 0,95 & 0,77 & 0,72 & 0,58 & 0,42 \\
     PVE (\%) & 41,85 & 22,05 & 12,86 & 8,53 & 7,42 & 4,79 & 2,49 \\
     PVEA (\%) & 41,85 & 63,90 & 76,76 & 85,29 & 92,71 & 97,05 & 100,00 \\ \hline
  \end{tabular}
\end{center}


``` {r, análise Residual das componentes principais, echo=FALSE,}
par(mfrow = c(1,1))
#biplot.psych {psych}
especief<-dados[,1]
# Componente 1
fit.model1 <- lm(cp1~especief)
m.residuo1 <- studres(fit.model1)
sumario <- summary(fit.model1)


#Componente 2
fit.model2 <- lm(cp2~especief)
m.residuo1 <- studres(fit.model2)
summary(fit.model2)

#Componente 3
fit.model3 <- lm(cp3~especief)
m.residuo1 <- studres(fit.model3)
summary(fit.model3)


par(mfrow =c(1,1))
plot(m.residuo1,ylim=c(min(-3,min(m.residuo1)),max(3,max(m.residuo1))),xlab="índice",ylab="resíduo studentizado", main = "Residuos do modelo com a Componente 1")
abline(-2,0,lty=2)
abline(2,0,lty=2)
abline(0,0,lty=2)

hist(m.residuo1,probability=TRUE,xlab="resíduo studentizado",main="Histograma dos resíduos",ylab="densidade")

qqPlot(m.residuo1,dist="norm",mean=0,sd=1,col.lines=1,grid="FALSE",xlab="quantil da N(0,1)",ylab=paste("quantil da distribuição do resíduo studentizado"),cex=1.2,id.cex=1.2)



comp.certas <- cbind(cp1, cp2, cp3)
#bla <-NULL
#bla[dados[,1]=="Torrens"]<-"T"
#bla[dados[,1]=="Carteri"]<-"C"
par(mfrow = c(1,1))
biplot(result.cp.cor,1:2)
biplot(result.cp.cor,c(1,3))
biplot(result.cp.cor,choices = 2:3, scale = 1, pc.biplot = TRUE)
```


```{r}

#residuos

hist(m.residuo1,probability=TRUE,xlab="resíduo studentizado",main="Histograma dos resíduos",ylab="densidade")

qqPlot((m.residuo1),dist="norm",mean=0,sd=1,col.lines=1,grid="FALSE",xlab="quantil da N(0,1)",ylab=paste("quantil da distribuição do resíduo studentizado"),cex=1.2,id.cex=1.2)

# hist(m.residuo2,probability=TRUE,xlab="resíduo studentizado",main="Histograma dos resíduos",ylab="densidade")
# 
# qqPlot((m.residuo2),dist="norm",mean=0,sd=1,col.lines=1,grid="FALSE",xlab="quantil da N(0,1)",ylab=paste("quantil da distribuição do resíduo studentizado"),cex=1.2,id.cex=1.2)
# 
# hist(m.residuo3,probability=TRUE,xlab="resíduo studentizado",main="Histograma dos resíduos",ylab="densidade")
# 
# qqPlot((m.residuo3),dist="norm",mean=0,sd=1,col.lines=1,grid="FALSE",xlab="quantil da N(0,1)",ylab=paste("quantil da distribuição do resíduo studentizado"),cex=1.2,id.cex=1.2)

```

```{r}
  source("gg_qq.r")
  temp <- rstudent(fit.model1)
  teste <- c("Carteri", "Torrens")
  gg_qq(temp)
```

```{r}
# IC TORRENS
ic.torrens <- summary(fit.model1)$coefficients[[1]] + c(-1,1)*summary(fit.model1)$coefficients[[3]]*qnorm(0.975)

# IC CARTERI
ic.carteri <- summary(fit.model1)$coefficients[[2]] + summary(fit.model1)$coefficients[[1]] + c(-1,1)*summary(fit.model1)$coefficients[[3]]*qnorm(0.975)
```

